# See https://github.com/novus/salat/blob/master/.travis.yml
language: scala
scala:
   - 2.12.15
   - 2.13.6
jdk:
  - oraclejdk8

script:
  - sbt clean coverage +test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)